### ISSUE TITLE
  Missing link or links in documentation object 'generate_download_filename.Rd':

### ISSUE THREAD

**Issue by emmavestesson** [HFAnalyticsLab/monstR#29]
Hi Neale, 
You started linking to a vignette from {whisker} but the link doesn't work so running `check()`
 Missing link or links in documentation object 'generate_download_filename.Rd':  ‘whisker’

I think it is linked to this line of code

https://github.com/HFAnalyticsLab/monstR/blob/869679ac57f70de4c1138b3dcf220e025b139df6/R/util.R#L67

I can't see a vignette for the whisker package btw.

**Comment by sw1nn** [comment]
As discussed, I don't know why the `\link{}` doesn't work. It's not actually adding much, so maybe remove it to avoid the warning.
