### ISSUE TITLE
ons_available_datasets not found

### ISSUE THREAD

**Issue by emmavestesson** [HFAnalyticsLab/monstR#3]
The ons_available_datasets function doesn't work. 

![image](https://user-images.githubusercontent.com/31949401/84149149-e5a69e00-aa57-11ea-846f-57b60179a752.png)

**Comment by sw1nn** [comment]
If you are using a local package you need to run ```devtools::load_all()``` - when the package is on CRAN this won't be necessary

**Comment by emmavestesson** [comment]
I built it and installed the package using install.packages so I though I wouldn't need to use load_all. That gets me one step closer but I still get an error saying that it can't find function select. 

``` r
library(THFOpenDataPipeline)
devtools::load_all('redacted_path/Open_data_pipelines')
#> Loading THFOpenDataPipeline
datasets <- ons_datasets_setup()
ons_available_datasets(datasets)
#> Error in select(., id): could not find function "select"
```

<sup>Created on 2020-06-09 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

 When I run check I get this as one of the warnings 
  'ons_available_datasets: no visible binding for global variable ‘id’' which I think might be linked to this problem.
