### ISSUE TITLE
'A required privilege is not held by the client'

### ISSUE THREAD

**Issue by SimonCRUK** [HFAnalyticsLab/monstR#31]
I'm getting an error whenever I try to collect any data.

```
Warning message:
In file.symlink(destfile, linkfile) :
  cannot symlink 'mypath\data\raw\ons\weekly-deaths-region\covid-19\weekly-deaths-region-v13.csv' to 'mypath/data/raw/ons/weekly-deaths-region/covid-19/weekly-deaths-region-vLATEST.csv', reason 'A required privilege is not held by the client'
```
The error does not occur if I run R Studio as an Administrator.

I'm using R 4.0.2 and R Studio 1.3.959 on Windows 10.

**Comment by emmavestesson** [comment]
Hi, 

Thanks for using the package and flagging an issue. 

Would you be able to post the code that caused the error message?  To me this looks like a permissions issue. Could your try a path that you know you have read and write permissions for?  Does it download any data or create a new folder structure? The message you have copied is a warning (as opposed to an error) so it wouldn't necessarily stop it.

**Comment by SimonCRUK** [comment]
Hello Emma,

I used the example code on the github page:

`monstr_pipeline_defaults() %>%  # Uses the monstr 'standards' for location and format
  ons_datasets_setup() %>% 
	ons_dataset_by_id("weekly-deaths-region") %>%
	ons_download(format="csv") %>%
	monstr_read_file() %>%  
	monstr_clean() %>%
	monstr_write_clean(format="all")
`

I have read and write permission for the folder it is downloading to. So far as I can see it generates the folders and data, the only file not generated is a symlink file. I'm not sure what this file does but it is generated when I run R Studio as an administrator and use the same code.

**Comment by sw1nn** [comment]
The 'Create Symbolic links' windows permission is required. 

Background on Symbolic Links - [Here](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/create-symbolic-links)

We are reviewing whether we should modify our approach wrt symbolic links if this permission is not widely available to unprivileged users.

**Comment by Lextuga007** [comment]
I get the same error. The difficulty is that most public sector systems will have a restriction on creating folders in the default drives. Is there anyway the code can be altered to either produce just the objects that can be saved or to have the user where to save it?

**Comment by sw1nn** [comment]
> I get the same error. The difficulty is that most public sector systems will have a restriction on creating folders in the default drives. Is there anyway the code can be altered to either produce just the objects that can be saved or to have the user where to save it?

- We've made the creation of the symlink optional, default is not to create it.
- You can supply your own root directory and directory layout by supplying a suitable set of defaults to `ons_datasets_setup()`

**Comment by fiona-grimm** [comment]
@all-contributors please add @SimonCRUK  for bug

**Comment by fiona-grimm** [comment]
@all-contributors please add @Lextuga007  for bug
