### ISSUE TITLE
Historical data for registered deaths

### ISSUE THREAD

**Issue by Lextuga007** [HFAnalyticsLab/monstR#42]
Is it possible to get data further back for ONS registered deaths through the API or is it only 2020? Could the historical data be linked to the nhsrdatasets package which goes from 2010 to 2019 and is on CRAN?

**Comment by emmavestesson** [comment]
Hi, 

Sorry about my slow reply. You can get historical death data using `monstR` by specifying the edition. See example below for the weekly deaths broken down by age and sex. To find out what editions of a dataset are available you can use `ons_available_editions( id = 'ID_of_data')

`monstr_pipeline_defaults() %>% 
  ons_datasets_setup() %>% 
  ons_dataset_by_id("weekly-deaths-age-sex", edition = '2010-19') %>%
  ons_download(format="csv") %>%
  monstr_read_file() %>%  
  monstr_clean() %>%
  monstr_write_clean(format="all")`

**Comment by Lextuga007** [comment]
Thank you - it looks like it defaults to this edition but the following doesn't give any more information past January 2021:

monstr_pipeline_defaults() %>%  # Uses the monstr 'standards' for location and format
  ons_datasets_setup() %>% 
  ons_dataset_by_id("weekly-deaths-region") %>%
  ons_download(format="csv") %>%
  monstr_read_file() %>%  
  monstr_clean() %>%
  monstr_write_clean(format="all")
