### ISSUE TITLE
week_number column as integer 

### ISSUE THREAD

**Issue by Lextuga007** [HFAnalyticsLab/monstR#43]
Could a column be added to the weekly-deaths-region_v14 for week numbers only as an integer as it isn't possible to order on the week_number column as it is a character column (each week number is preceded by 'week-')?

**Comment by fiona-grimm** [comment]
Hi Zoe, 
Unfortunately, we don't have control over the data or specific columns you can request through the ONS API. monstR is just intended to make the API call easier for R users. 

You might be able to solve the issues with the week number column using the str_remove() function from the {stringr} package. Once you've gotten rid of the "week-" part of the string, it should be easier to convert it to numeric and to use it to order the data in a more sensible way. Let me know if that helps!

**Comment by Lextuga007** [comment]
Hello. Thanks for this. It's odd that it's provided as a character from the API as it's released in the excel spreadsheet just as an integer, ah well.  I'm happy to write something for a vignette if that's useful.

**Comment by Lextuga007** [comment]
This ties in with the nhsrdatasets package which has historical ONS mortality data so I'm going to write a vignette there on how to combine it with updated data from monstR.  Perhaps that vignette can be shared here?
