### ISSUE TITLE
ons_available_datasets() function not working

### ISSUE THREAD

**Issue by sg-peytrignet** [HFAnalyticsLab/monstR#49]
Hello,

The function ons_available_datasets(), which used to work, has stopped returning the list of available datasets. Could it be due to something in the underlying API having changed?

Thanks

Seb

``` r
library(monstR)

datasets <- monstR::ons_available_datasets()
#> Error: Can't subset columns that don't exist.
#> x Column `unit_of_measure` doesn't exist.
```

<sup>Created on 2020-11-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by emmavestesson** [comment]
Hi Seb, 

There were some updates happening to the ONS API last week which is why you were having an issue. After the update there seems to be one column that is missing (publisher) so I've dropped it as we we don't use it. I've replaced it with publications information instead.
