### ISSUE TITLE
ons_datasets_setup() "ERROR [] file not created"

### ISSUE THREAD

**Issue by SomeGuyCalledJ** [HFAnalyticsLab/monstR#9]
If thf_pipeline_defaults() not used in argument, the function will throw an error:

INFO [2020-06-26 12:00:15] Edition not specified, defaulting to  latest version
INFO [2020-06-26 12:00:15] Retrieving dataset metadata from https://api.beta.ons.gov.uk/v1/datasets/weekly-deaths-region/editions/covid-19/versions/9
INFO [2020-06-26 12:00:15] Downloading data from https://download.beta.ons.gov.uk/downloads/datasets/weekly-deaths-region/editions/covid-19/versions/9.csv
INFO [2020-06-26 12:00:15] Creating directory 
ERROR [2020-06-26 12:00:16] file  Not created!
Warning messages:
1: Unknown or uninitialised column: `download_filename_template`. 
2: In dir.create(dir, recursive = TRUE) :
  cannot create dir '', reason 'No such file or directory'
3: In file.rename(from = tmp, to = destfile) :
  cannot rename file 'C:\Users\<user>\AppData\Local\Temp\RtmpCMsDo5\file65b026fb7f5c' to '', reason 'The system cannot find the path specified'

**Comment by emmavestesson** [comment]
Hi John, 

Are you talking about this snippet of code in the vignette? I've noticed a similar thing with a different function so just wanted to make sure. 

`ons_datasets_setup() %>%
	ons_dataset_by_id("weekly-deaths-local-authority") %>%
	ons_download(format="csv")`

**Comment by SomeGuyCalledJ** [comment]
Aye, that's the snippet

**Comment by sw1nn** [comment]
This is kinda intentional, but error reporting should be improved. The problem with having a default is that you can quickly end up downloading large files and filling up disks causing machines to crash.

A good pragmatic improvement would be to validate that some defaults have been provided, and giving an onerous WARN log message saying something like 'You didn't set the default locations for downloads, we're carrying on but at your own risk!"

**Comment by sw1nn** [comment]
Thinking about this a bit more, it makes more sense IMO to pass the defaults in at the start something like:
```
ons_datasets_setup(thf_pipeline_defaults()) %>%
	ons_dataset_by_id("weekly-deaths-local-authority") %>%
	ons_download(format="csv") %>%
	thf_read_file() %>%  
	thf_clean() %>%
	thf_write_clean(format="all")

```

**Comment by emmavestesson** [comment]
I agree that there shouldn't be a default as files will be downloaded. I think a warning is a good idea. Can we also add an example using the thf_pipeline_defaults() function and one using user specified file paths? I've been adding examples as 'dontrun' to avoid querying the API.

**Comment by sw1nn** [comment]
Good idea, I'll add those
